# Stage 1: Build
FROM node:20-alpine AS build

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY /frontend .

RUN npm run build

# Stage 2: Production
FROM nginx:stable-alpine AS production

# Copy the build output from the dist folder into the Nginx html directory
COPY --from=build /app/dist /usr/share/nginx/html

# Copy the Certbot initialization script
COPY init-certbot.sh /init-certbot.sh

# Give execution permissions to the script
RUN chmod +x /init-certbot.sh

# Expose port 80 to allow access to the app
EXPOSE 80 443

# Run Nginx in the foreground
CMD ["sh", "-c", "nginx & sleep 3 && /init-certbot.sh && tail -f /dev/null"]


